apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "latest-test"
  description: "latest-test"
  annotations:
    github.com/project-slug: fp-mt-test-org/latest-test
    backstage.io/techdocs-ref: url:https://github.com/fp-mt-test-org/latest-test
    backstage.io/kubernetes-id: latest-test
spec:
  type: library
  lifecycle: experimental
  owner: "Product Infrastructure"
